backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
# This line should *not* be indented
publish_mode: editorial_workflow
# This line should *not* be indented
media_folder: "static/images/uploads" # Media files will be stored in the repo under images/uploads
collections:
  - name: "recette" # Used in routes, e.g., /admin/collections/blog
    label: "Recette" # Used in the UI
    folder: "static/content/recettes" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "titre", name: "titre", widget: "string"}
      - {label: "Corps", name: "body", widget: "markdown"}